[[plugins]]
package = "@netlify/plugin-gatsby"

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "frame-ancestors 'none'"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
